version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./data:/data
      - /app/tmp  # For air's tmp directory
    restart: unless-stopped
    command: air

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.next  # Prevent overwriting build
    depends_on:
      - backend
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"

volumes:
  data: